import type { PropertyWithAgent } from "@shared/schema";

// Mock property data for demonstration purposes
export const mockProperties: PropertyWithAgent[] = [
  {
    id: 11,
    title: "Luxurious Family Home in Sandton",
    description: "Beautiful 4-bedroom family home with modern finishes, spacious living areas, and a stunning garden. Perfect for entertaining and family living.",
    price: "2850000",
    address: "15 Wisteria Lane",
    suburb: "Sandton",
    city: "Johannesburg",
    province: "Gauteng",
    postalCode: "2196",
    latitude: "-26.1076",
    longitude: "28.0567",
    propertyType: "house",
    bedrooms: 4,
    bathrooms: "3.5",
    area: 350,
    lotSize: "1200",
    yearBuilt: 2018,
    parking: "Double garage",
    features: ["Swimming Pool", "Garden", "Security", "Modern Kitchen", "Study"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"
    ],
    status: "active",
    agentId: 1,
    featured: true,
    views: 45,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    agent: {
      id: 1,
      name: "Sarah Williams",
      email: "sarah@realestate.com",
      phone: "+27 82 123 4567",
      avatar: "https://images.unsplash.com/photo-1494790108755-2616b89298aa?ixlib=rb-4.0.3&auto=format&fit=crop&w=256&q=80",
      bio: "Experienced real estate agent specializing in luxury properties in Sandton and surrounding areas.",
      specialties: ["Luxury Homes", "Investment Properties", "Commercial"],
      rating: "4.8",
      totalSales: 127,
      createdAt: new Date("2020-03-01")
    }
  },
  {
    id: 12,
    title: "Modern Apartment in Cape Town CBD",
    description: "Stunning 2-bedroom apartment with panoramic city and mountain views. Located in the heart of Cape Town with easy access to all amenities.",
    price: "1950000",
    address: "88 Loop Street",
    suburb: "Cape Town CBD",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "8001",
    latitude: "-33.9249",
    longitude: "18.4241",
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: "2.0",
    area: 120,
    lotSize: null,
    yearBuilt: 2020,
    parking: "One covered parking",
    features: ["City Views", "Mountain Views", "Balcony", "Modern Finishes", "Security"],
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"
    ],
    status: "active",
    agentId: 2,
    featured: false,
    views: 28,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-18"),
    agent: {
      id: 2,
      name: "Michael Thompson",
      email: "michael@realestate.com",
      phone: "+27 83 987 6543",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=256&q=80",
      bio: "Cape Town specialist with expertise in urban properties and investment opportunities.",
      specialties: ["Urban Living", "Apartments", "Investment"],
      rating: "4.6",
      totalSales: 89,
      createdAt: new Date("2019-08-15")
    }
  },
  {
    id: 13,
    title: "Beachfront Villa in Camps Bay",
    description: "Exclusive 5-bedroom villa with direct beach access and breathtaking ocean views. Premium location with world-class amenities.",
    price: "8500000",
    address: "22 Victoria Road",
    suburb: "Camps Bay",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "8005",
    latitude: "-33.9555",
    longitude: "18.3783",
    propertyType: "house",
    bedrooms: 5,
    bathrooms: "4.5",
    area: 480,
    lotSize: "800",
    yearBuilt: 2019,
    parking: "Triple garage",
    features: ["Ocean Views", "Beach Access", "Swimming Pool", "Wine Cellar", "Entertainment Area"],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"
    ],
    status: "active",
    agentId: 1,
    featured: true,
    views: 89,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-25"),
    agent: {
      id: 1,
      name: "Sarah Williams",
      email: "sarah@realestate.com",
      phone: "+27 82 123 4567",
      avatar: "https://images.unsplash.com/photo-1494790108755-2616b89298aa?ixlib=rb-4.0.3&auto=format&fit=crop&w=256&q=80",
      bio: "Experienced real estate agent specializing in luxury properties in Sandton and surrounding areas.",
      specialties: ["Luxury Homes", "Investment Properties", "Commercial"],
      rating: "4.8",
      totalSales: 127,
      createdAt: new Date("2020-03-01")
    }
  },
  {
    id: 14,
    title: "Penthouse in Umhlanga",
    description: "Luxury penthouse with panoramic ocean views in the heart of Umhlanga. Modern finishes and premium amenities throughout.",
    price: "4200000",
    address: "15 Lighthouse Road",
    suburb: "Umhlanga Rocks",
    city: "Durban",
    province: "KwaZulu-Natal",
    postalCode: "4320",
    latitude: "-29.7211",
    longitude: "31.0982",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: "3.0",
    area: 220,
    lotSize: null,
    yearBuilt: 2021,
    parking: "Two covered bays",
    features: ["Ocean Views", "Balcony", "Security", "Gym", "Concierge"],
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"
    ],
    status: "active",
    agentId: 3,
    featured: true,
    views: 67,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-22"),
    agent: {
      id: 3,
      name: "David Patel",
      email: "david@realestate.com",
      phone: "+27 84 555 9876",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=256&q=80",
      bio: "KwaZulu-Natal specialist focusing on coastal properties and luxury developments.",
      specialties: ["Coastal Properties", "Luxury Apartments", "New Developments"],
      rating: "4.7",
      totalSales: 94,
      createdAt: new Date("2020-11-10")
    }
  },
  {
    id: 15,
    title: "Garden Cottage in Stellenbosch",
    description: "Charming 3-bedroom cottage in the heart of the wine country. Perfect for those seeking tranquility and natural beauty.",
    price: "1650000",
    address: "47 Van Riebeeck Street",
    suburb: "Stellenbosch Central",
    city: "Stellenbosch",
    province: "Western Cape",
    postalCode: "7600",
    latitude: "-33.9321",
    longitude: "18.8602",
    propertyType: "house",
    bedrooms: 3,
    bathrooms: "2.0",
    area: 180,
    lotSize: "1500",
    yearBuilt: 1995,
    parking: "Single garage",
    features: ["Garden", "Wine Cellar", "Fireplace", "Mountain Views", "Historic Character"],
    images: [
      "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"
    ],
    status: "active",
    agentId: 2,
    featured: false,
    views: 34,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-19"),
    agent: {
      id: 2,
      name: "Michael Thompson",
      email: "michael@realestate.com",
      phone: "+27 83 987 6543",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=256&q=80",
      bio: "Cape Town specialist with expertise in urban properties and investment opportunities.",
      specialties: ["Urban Living", "Apartments", "Investment"],
      rating: "4.6",
      totalSales: 89,
      createdAt: new Date("2019-08-15")
    }
  }
];

export function getMockProperty(id: number): PropertyWithAgent | undefined {
  return mockProperties.find(property => property.id === id);
}

export function getMockProperties(): PropertyWithAgent[] {
  return mockProperties;
}